services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 5s
      timeout: 5s
      retries: 10
  app:
    image: app
    restart: always
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=mysql://root:root@db:3306/app
    depends_on:
      db:
        condition: service_healthy

volumes:
  db:
